[package]
name = "wazoo-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "wazoo_app"
path = "src/lib.rs"

[[bin]]
name = "wazoo"
path = "src/main.rs"

[dependencies]
wazoo-core.workspace = true
wazoo-scanner.workspace = true
wazoo-media.workspace = true
iced.workspace = true
tokio.workspace = true
log.workspace = true
env_logger.workspace = true
rand.workspace = true
rfd.workspace = true
regex.workspace = true
mimalloc.workspace = true

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

