[package]
name = "wazoo-scanner"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wazoo-core.workspace = true
walkdir.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
tokio.workspace = true
thiserror.workspace = true
chrono.workspace = true
