import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import { nextTick } from 'vue'
import SubtitleDisplay from '../SubtitleDisplay.vue'



const fullUserScript = `[Script Info]
; Script generated by Aegisub 9643-cibuilds-c61f149a3
; http://www.aegisub.org/
Title: 3-gatsu no Lion 06
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1920
PlayResY: 1080
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Fontin Sans Rg,69,&H00EBEFF6,&H000000FF,&H00091A04,&HBE000000,-1,0,0,0,100,100,0,0,1,3.6,1.5,2,135,135,53,1
Style: signs,Fontin Sans Rg,75,&H00FFFFFF,&H000000FF,&H000A162D,&H00000000,0,0,0,0,100,100,0,0,1,0,0,5,15,15,15,1
Style: titles,EFN Dekorator,53,&H006C6A6B,&H000000FF,&H000A162D,&H00000000,0,0,0,0,100,100,3,0,1,0,0,5,15,15,15,1
Style: OP,Gloria Hallelujah,75,&H00989480,&H000000FF,&H00FFFFFF,&HBE000000,-1,0,0,0,100,100,0,0,1,3.3,0,1,60,60,30,1
Style: ED,The Great Escape,78,&H00EBEFF6,&H000000FF,&H00EEB24F,&HBE000000,-1,0,0,0,100,100,0,0,1,3.3,0,3,60,60,30,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 5,0:01:31.48,0:01:31.48,Default,chapter,0,0,0,,{Chapter 11: Child of God (Part One)}
Dialogue: 5,0:01:48.00,0:01:50.60,Default,,0,0,0,,{\\i1}Without thinking, it came out of my mouth.
Dialogue: 5,0:01:52.48,0:01:54.00,Default,,0,0,0,,I want to go somewhere.
Dialogue: 5,0:01:54.33,0:01:55.01,Default,,0,0,0,,Huh?
Dialogue: 5,0:01:55.01,0:01:56.43,Default,,0,0,0,,Where?
Dialogue: 5,0:01:57.55,0:01:59.13,Default,,0,0,0,,Where do you want to go, Rei{**-kun}?
Dialogue: 5,0:02:17.46,0:02:21.49,Default,,0,0,0,,With meat dumplings, \\Nshrimp in chili sauce, and almond jelly!
Dialogue: 5,0:24:51.98,0:24:55.49,Default,,0,0,0,,{\\an3\\i1}I hope you watch the next episode of \\N"March comes in like a lion"!
Dialogue: 1,0:20:52.17,0:20:56.31,ED,,0,0,0,,{\\3c&H7A4F2F&\\1a&HFF&\\blur3\\fad(250,250)\\t(706,1082,\\3c&H7A5C45&)\\t(1082,1457,\\3c&H543620&)\\t(1499,2750,\\3c&H896D57&)\\t(2750,3501,\\3c&H7A4F2F&)}Like a resplendent meteor shower
Dialogue: 0,0:20:56.57,0:21:01.36,ED,,0,0,0,,{\\bord1.5\\3c&H000000&\\1a&HFF&\\blur3\\fad(250,250)\\t(1520,2646,\\3c&H968477&)\\t(2646,3321,\\3c&H715139&)\\t(3321,4398,\\3c&HA79282&)}Your words enter my ears and catch fire
Dialogue: 0,0:21:01.86,0:21:05.99,ED,,0,0,0,,{\\pos(1860,1072.5)\\bord1.5\\3c&HA69C25&\\1a&HFF&\\blur4.5\\fad(250,250)}They come together like a school of fish
Dialogue: 0,0:13:21.65,0:13:23.11,signs,,0,0,0,,{\\pos(223.5,144)\\fscx52\\fscy52\\frz1.147\\fnFranklin Gothic Medium\\c&H3D4A4B&\\alpha&HA0&\\blur4.05}Tokyo
Dialogue: 1,0:13:21.65,0:13:23.11,signs,,0,0,0,,{\\pos(223.5,144)\\fscx52\\fscy52\\frz1.147\\fnFranklin Gothic Medium\\c&H445A5C&\\blur1.35}Tokyo
Dialogue: 0,0:14:53.12,0:14:57.12,signs,,0,0,0,,{=26=33}{\\move(1011,192,1182.405,327.405,23,3985)\\fscx74\\fscy74\\frz350.6\\fax0.13\\fnFranklin Gothic Demi\\c&H000000&\\1a&H64&\\blur5.4}The 5th in History
`

describe('SubtitleDisplay.vue', () => {
  it('mounts without crashing when empty', () => {
    const wrapper = mount(SubtitleDisplay, {
      props: {
        subtitleContent: '',
        videoElement: null,
        enabled: true
      }
    })
    expect(wrapper.exists()).toBe(true)
    expect(wrapper.find('.subtitle-overlay').exists()).toBe(true)
  })

  it('renders styled ASS subtitles with video element', async () => {
    const video = document.createElement('video')
    document.body.appendChild(video)

    const wrapper = mount(SubtitleDisplay, {
      props: {
        subtitleContent: fullUserScript,
        videoElement: video,
        enabled: true
      },
      attachTo: document.body
    })

    await nextTick()
    await nextTick()

    const ass = (wrapper.vm as any).getASS()
    expect(ass).toBeDefined()

    // Toggling enabled to false calls hide and toggles class
    await wrapper.setProps({ enabled: false })
    await nextTick()
    expect(wrapper.classes()).toContain('hidden')

    // Toggling enabled to true calls show and removes class
    await wrapper.setProps({ enabled: true })
    await nextTick()
    expect(wrapper.classes()).not.toContain('hidden')

    wrapper.unmount()
    video.remove()
  })

  it('handles SRT subtitles and converts to ASS', async () => {
    const video = document.createElement('video')
    document.body.appendChild(video)

    const srt = `1\n00:00:01,000 --> 00:00:04,000\n<i>Test line</i>\n`
    const wrapper = mount(SubtitleDisplay, {
      props: {
        subtitleContent: srt,
        videoElement: video,
        enabled: true
      },
      attachTo: document.body
    })

    await nextTick()
    await nextTick()

    const ass = (wrapper.vm as any).getASS()
    expect(ass).toBeDefined()

    wrapper.unmount()
    video.remove()
  })

  it('re-initializes ASS when subtitleContent changes dynamically', async () => {
    const video = document.createElement('video')
    document.body.appendChild(video)

    const initialAss = `[Script Info]\nTitle: Test 1\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\nDialogue: 0,0:00:01.00,0:00:05.00,Default,,0,0,0,,Hello 1`
    const updatedAss = `[Script Info]\nTitle: Test 2\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\nDialogue: 0,0:00:02.00,0:00:06.00,Default,,0,0,0,,{\\b1}Hello 2{\\b0}`


    const wrapper = mount(SubtitleDisplay, {
      props: {
        subtitleContent: initialAss,
        videoElement: video,
        enabled: true
      },
      attachTo: document.body
    })

    await nextTick()
    await nextTick()

    const firstAss = (wrapper.vm as any).getASS()
    expect(firstAss).toBeDefined()

    await wrapper.setProps({ subtitleContent: updatedAss })
    await nextTick()
    await nextTick()

    const secondAss = (wrapper.vm as any).getASS()
    expect(secondAss).toBeDefined()
    expect(secondAss).not.toBe(firstAss)

    wrapper.unmount()
    video.remove()
  })

  it('supports simultaneous overlapping subtitles across styles and layers', async () => {
    const video = document.createElement('video')
    document.body.appendChild(video)

    const overlappingAss = `[Script Info]
Title: Overlapping Test
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,60,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3,2,2,40,40,40,1
Style: TopSign,Arial,70,&H0000FFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3,2,8,40,40,40,1
Style: Karaoke,Arial,50,&H00FF00FF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3,2,1,40,40,40,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:10.00,Default,,0,0,0,,Standard spoken dialogue
Dialogue: 1,0:00:01.00,0:00:10.00,TopSign,,0,0,0,,{\\pos(960,100)}Top screen sign
Dialogue: 0,0:00:01.00,0:00:10.00,Karaoke,,0,0,0,,Bottom-left song lyrics
`
    const wrapper = mount(SubtitleDisplay, {
      props: {
        subtitleContent: overlappingAss,
        videoElement: video,
        enabled: true
      },
      attachTo: document.body
    })

    await nextTick()
    await nextTick()

    const ass = (wrapper.vm as any).getASS()
    expect(ass).toBeDefined()

    wrapper.unmount()
    video.remove()
  })
})

