[env]
PKG_CONFIG_PATH = { value = "/home/klo/wazoo/wazoo-rs/.sysroot/usr/lib/x86_64-linux-gnu/pkgconfig", relative = false }
LIBRARY_PATH = { value = "/home/klo/wazoo/wazoo-rs/.sysroot/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu", relative = false }

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-L", "native=/home/klo/wazoo/wazoo-rs/.sysroot/usr/lib/x86_64-linux-gnu",
    "-C", "link-arg=-Wl,-rpath,/home/klo/wazoo/wazoo-rs/.sysroot/usr/lib/x86_64-linux-gnu",
]
