[package]
name = "wazoo-media"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wazoo-core.workspace = true
iced = { workspace = true }
iced_wgpu = { workspace = true }
bytemuck = { workspace = true }
tokio.workspace = true
rand.workspace = true
log.workspace = true
url.workspace = true
thiserror.workspace = true
serde.workspace = true

