/*!
 * ALKALI SOFTWORKS - Wazoo
 *
 * Application Message Definitions
 *
 * Enumerates all user interactions, playback commands, background scanner updates,
 * timer ticks, and window system events routed through the Iced application loop.
 */

use iced::{Point, Size, event::Status, keyboard::Key, window::Id};
use std::sync::{Arc, Mutex};
use std::time::Duration;
use wazoo_core::Bookmark;
use wazoo_media::{PlayerId, VideoHandle};
use wazoo_scanner::ScanProgress;

#[derive(Debug, Clone)]
pub enum Message {
    // Window management & Events
    WindowIdReceived(Id),
    WindowMoved(Id, Point),
    WindowResized(Id, Size),
    WindowFocused,
    WindowUnfocused,
    ModifiersChanged(iced::keyboard::Modifiers),
    GainWindowFocus,
    PreloadedPlayerReady(Arc<Mutex<Option<Result<VideoHandle, String>>>>),
    CursorMoved(Id, Point),
    CursorLeft,
    RightClickPressed(Id),
    KeyPressed(Key, Status),
    KeyReleased(Key),
    MinimizeWindow,
    MaximizeWindow,
    CloseApp,
    DragWindow,
    DragResize(iced::window::Direction),
    TitleBarPressed,
    LeftClickReleased,
    ToggleDropdownMenu,
    CloseDropdownMenu,
    OpenMenuModal,
    CloseMenuModal,
    ToggleFilePicker,
    ToggleFolderCollapse(String),
    FilePickerSearchChanged(String),
    ApplyFilePickerSearch,
    ToggleHistoryDrawer,
    CloseHistoryDrawer,
    HistorySearchChanged(String),
    ClearPlayHistory,
    PlayFileInFocused(String),
    SelectSearchFolder(String),
    ToggleSearchFolder(String),
    ResetSearchFolder,
    RemoveActiveSearchFolder(String),
    SetWindowOpacity(f32),

    // Playback controls
    PlayerClicked(PlayerId),
    TogglePlay(PlayerId),
    TogglePlayFocused,
    NextVideo(PlayerId),
    PrevVideo(PlayerId),
    AutoAdvanceVideo(PlayerId),
    NextVideoFocused,
    PrevVideoFocused,
    Seek(PlayerId, Duration),
    SeekRatio(PlayerId, f32),
    SeekRelativeFocused(f64),
    StepFrameForwardFocused,
    StepFrameBackwardFocused,
    PlayerHovered(PlayerId),
    PlayerUnhovered(PlayerId),
    SetVolume(PlayerId, f64),
    AdjustVolumeFocused(f64),
    SelectAudioTrack(PlayerId, i64),
    ToggleAudioMenu(PlayerId),
    CloseAudioMenu,
    TogglePlayerMute(PlayerId),
    ToggleMuteFocused,
    ToggleGlobalMute,
    GlobalUnmute,
    ToggleShuffleMode,
    TogglePlayerShuffle(PlayerId),
    MarkInFocused,
    MarkOutFocused,
    ClearMarkInFocused,
    ClearMarkOutFocused,
    ClearLoop(PlayerId),
    ClearLoopFocused,

    // Layout & Modes
    CycleLayout,
    SetPlayerCount(usize),
    ToggleScrollMode,
    ToggleFlipMode,
    ToggleAlwaysOnTop,
    SetScrollSpeed(f32),
    AdjustScrollSpeed(f32),
    AddNewPlayer,
    RemoveFocusedPlayer,
    CycleFocusedPlayer,
    SetFocusedPlayer(usize),

    // Modals & UI
    OpenSearchModal,
    CloseSearchModal,
    SearchInputChanged(String),
    RemoveSearchTag(usize),
    PerformSearch,
    ClearSearch,
    OpenSettingsModal,
    CloseSettingsModal,
    SetSettingsTab(crate::app::SettingsTab),
    SetGamma(f32),
    SetContrast(f32),
    SetBrightness(f32),
    SetSaturation(f32),
    SetPlaybackSpeed(f32),
    SetBufferDuration(u32),
    SetBufferSize(u32),
    SetFlipInterval(u64),
    ResetPlaybackOptions,
    ToggleDefaultPlayer,
    OpenAlkaliWebsite,
    SetLanguage(String),
    OpenHelpModal,
    CloseHelpModal,
    FolderInputChanged(String),
    PickFolders,
    FoldersSelected(Vec<String>),
    AddMediaFolder,
    RemoveMediaFolder(String),
    ClearMiscVideos,
    StartScan,
    ScanProgressUpdate(u64, ScanProgress),
    ScanFinished(u64, Result<usize, String>),
    ToggleSubtitles,
    ToggleTranscript,
    ToggleTranscriptForPlayer(PlayerId),
    CloseTranscript,
    TranscriptSearchChanged(String),
    TranscriptLoaded(String, usize, Vec<wazoo_media::SubtitleCue>),
    SeekToSubtitle(f64),
    ToggleTranscriptSubtitleMenu,
    CloseTranscriptSubtitleMenu,
    SelectTranscriptSubtitleTrack(usize, i64),
    EscapePressed,

    // Bookmarks & wazoo-js shortcuts
    ToggleBookmarksModal,
    CloseBookmarksModal,
    AddBookmarkFocused,
    RemoveBookmarkFocused,
    RemoveBookmark(usize),
    JumpToBookmark(Bookmark),
    RandomSeekFocused,
    ShowTitleOverlay,

    // Timers & Ticks
    AnimationTick,
    VideoFrameTick,
    WatchdogTick,
    DismissToast,
    ModalCardClicked,
}
